// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjfybocagqjdculreuol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZnlib2NhZ3FqZGN1bHJldW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjE5NjgsImV4cCI6MjA3Mzc5Nzk2OH0.UPqwDgW6X5V00l2n54QSVYac7TLOpfgnUe1mRJLCVjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});